mountShell('agents'); const out = document.getElementById('out'); let AGENTS = [];
document.getElementById('new').onclick = () => location.href = 'create.html';
const pinModal = (title, r) => modal({ title, body: `<p style="color:var(--muted)">Give this to ${esc(r.name)} in person or by phone.</p><div class="pin">${esc(r.pin)}</div><div class="alert info">Shown only once. Only a secure hash is stored.</div>`, actions: [{ label: 'Done', kind: 'primary' }] });
function detail(a) {
  const d = drawer(`${a.name} · ${a.code}`, '<div id="dt"></div><div id="dv"></div>'); const dv = d.el.querySelector('#dv');
  const views = [async () => dl({ 'Agent ID': a.code, Mobile: '+91 ' + esc(a.mobile), Address: esc(a.address || '—'), 'ID proof': a.id_proof ? `${esc(a.id_proof.type)} •••• ${a.id_proof.last4}` : '—', Customers: a.customers, Joined: a.joined, Status: pill(a.status) }),
    async () => { const p = (await PaymentService.list()).filter((x) => x.by === a.name); return table([{ h: 'Receipt', f: (x) => x.receipt }, { h: 'Date & time', f: (x) => x.when }, { h: 'Customer', f: (x) => esc(x.customer) }, { h: 'Amount', f: (x) => fmt.money(x.amount), r: 1 }], p, 'No collections yet.'); },
    async () => dl({ 'Collected today': fmt.money(a.collectedToday), 'Pending today': fmt.money(a.pendingToday), 'Collection %': a.rate + '%' }) + `<div class="bar"><i style="width:${a.rate}%"></i></div>`,
    async () => { const l = (await AuditService.list()).filter((x) => x.entity === a.code); return l.length ? l.map((x) => `<div class="kv"><span><b style="color:var(--ink)">${x.action}</b><br>${esc(x.detail)}<br><small>${x.time} · ${esc(x.actor)}</small></span></div>`).join('') : '<div class="empty">No audit entries yet.</div>'; }];
  const show = async (i) => { loading(dv); try { dv.innerHTML = await views[i](); } catch (e) { failed(dv, e); } };
  tabs(d.el.querySelector('#dt'), ['Overview', 'Collections', 'Performance', 'Audit'], show); show(0);
  dv.insertAdjacentHTML('afterend', `<div style="margin-top:18px;display:flex;gap:8px;flex-wrap:wrap"><button class="btn neutral" id="ed">Edit agent</button><button class="btn neutral" id="rp">Reset PIN</button><button class="btn ${a.status === 'active' ? 'danger' : 'primary'}" id="dx">${a.status === 'active' ? 'Deactivate' : 'Activate'}</button></div>`);
  d.el.querySelector('#ed').onclick = () => location.href = 'create.html?code=' + a.code;
  d.el.querySelector('#rp').onclick = () => modal({ title: `Reset PIN for ${a.name}?`, body: `<p style="color:var(--muted)">${a.code} · +91 ${esc(a.mobile)}</p><div class="alert warn" style="margin-top:10px">The current PIN stops working immediately.</div>`, actions: [{ label: 'Cancel' }, { label: 'Reset PIN', kind: 'primary', onClick: async (c) => { try { const r = await AgentService.reset(a); c(); d.close(); pinModal('New temporary PIN', { name: a.name, pin: r.pin }); } catch (e) { toast(e.message); } } }] });
  d.el.querySelector('#dx').onclick = () => a.status === 'active' && a.customers > 0 ? transferFirst(a, d) : modal({ title: `${a.status === 'active' ? 'Deactivate' : 'Activate'} ${a.name}?`, body: a.status === 'active' ? '<p style="color:var(--muted)">They will not be able to log in.</p>' : '', actions: [{ label: 'Cancel' }, { label: 'Confirm', kind: 'primary', onClick: async (c) => { try { await AgentService.setActive(a, a.status !== 'active'); c(); d.close(); toast('Agent updated'); load(); } catch (e) { toast(e.message); } } }] });
}
function transferFirst(a, d) {
  const others = AGENTS.filter((x) => x.id !== a.id && x.status === 'active');
  modal({ title: 'Transfer customers first', body: `<div class="alert warn">${esc(a.name)} still has ${a.customers} customer${a.customers > 1 ? 's' : ''}. An agent can't be deactivated while customers are assigned.</div><div class="field l"><label>Move all customers to *</label><select class="input" id="to"><option value="">Select an agent…</option>${others.map((x) => `<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div>`,
    actions: [{ label: 'Cancel' }, { label: 'Transfer & deactivate', kind: 'danger', onClick: async (c, b, o) => { const to = o.querySelector('#to').value; if (!to) return toast('Choose an agent'); b.disabled = true;
      try { const mine = (await Api.portfolio()).filter((x) => x.agent?.id === a.id); for (const cu of mine) await CustomerService.transfer(cu.id, to, 'Agent deactivated'); await AgentService.setActive(a, false); c(); d.close(); toast('Customers transferred and agent deactivated'); load(); } catch (e) { toast(e.message); b.disabled = false; } } }] });
}
function load() { loading(out); AgentService.list().then((r) => { AGENTS = r; document.getElementById('count').textContent = `${r.length} agents`; out.innerHTML = table([{ h: 'Agent', f: (a) => `<div class="who"><span class="avatar">${fmt.initials(a.name)}</span><div><b>${esc(a.name)}</b><small>${esc(a.code)}</small></div></div>` }, { h: 'Mobile', f: (a) => '+91 ' + esc(a.mobile) }, { h: 'Customers', f: (a) => a.customers, r: 1 }, { h: 'Collected today', f: (a) => fmt.money(a.collectedToday), r: 1 }, { h: 'Joined', f: (a) => esc(a.joined) }, { h: 'Status', f: (a) => pill(a.status) }], r); out.querySelectorAll('tr.click').forEach((tr) => tr.onclick = () => detail(r[tr.dataset.i])); }).catch((e) => failed(out, e)); }
load();
