mountShell('chits');
const P = new URLSearchParams(location.search), id = P.get('id'), out = document.getElementById('out'); let c;
async function load() { c = await ChitService.get(id); const l = (await ChitService.list()).find((x) => String(x.id) === String(id)); if (l) { c.customer = l.customer; c.agent = l.agent; c.disbursement = l.disbursement; } }
const rowsT = (r) => table([{ h: '#', f: (i) => 'Day ' + i.sequence }, { h: 'Date', f: (i) => i.due_date }, { h: 'Due', f: (i) => i.amount, r: 1 }, { h: 'Paid', f: (i) => i.paid, r: 1 }, { h: 'Remaining', f: (i) => fmt.paise(i.remaining_paise), r: 1 }, { h: 'Status', f: (i) => pill(i.status.replace('_', ' ')) }], r, 'Nothing to show. Try changing the filters.');
async function schedule() { loading(out); const r = await ChitService.schedule(id); let f = 'all';
  const draw = () => { out.innerHTML = `<b>Repayment schedule · ${c.chit_code}</b><div id="fs" style="margin:10px 0"></div>${rowsT(r.filter((i) => f === 'all' || i.status === f))}`; chips(out.querySelector('#fs'), ['All', 'Paid', 'Overdue', 'Due today', 'Upcoming'], (i) => { f = ['all', 'paid', 'overdue', 'due_today', 'upcoming'][i]; draw(); }, ['all', 'paid', 'overdue', 'due_today', 'upcoming'].indexOf(f)); }; draw(); }
function disbursement() {
  if (c.status !== 'pending') return out.innerHTML = `<div class="card" style="max-width:520px"><b>Disbursement</b>${dl({ Status: pill(c.status === 'cancelled' ? 'cancelled' : 'completed'), Amount: c.loan_amount })}${c.disbursement ? dl({ Method: label(c.disbursement.method), Date: dmy(c.disbursement.disbursed_on), Reference: esc(c.disbursement.reference || '—') }) : ''}</div>`;
  out.innerHTML = `<div class="two" style="grid-template-columns:1fr 1fr"><form class="card" id="df"><b>Record disbursement</b><div class="alert warn">The loan amount has not been given yet. The chit stays Pending until a completed disbursement is recorded.</div>
  <div class="field l"><label>Method *</label><div class="row2"><label class="opt"><input type="radio" name="method" value="cash" checked> Cash</label><label class="opt"><input type="radio" name="method" value="bank_transfer"> Bank transfer</label></div></div>
  <div class="row2"><div class="field l"><label>Date *</label><input class="input" type="date" name="disbursed_on" value="${new Date().toISOString().slice(0, 10)}"></div><div class="field l"><label>Amount</label><input class="input" disabled value="${esc(c.loan_amount)}"></div></div>
  <div class="field l" id="rf" hidden><label>Reference number *</label><input class="input" name="reference" placeholder="e.g. NEFT-40177"></div>
  <div class="field l"><label>Result *</label><select class="input" name="status"><option value="completed">Completed</option><option value="failed">Failed</option></select></div>
  <div class="field l"><label>Note</label><textarea class="input" name="note" style="height:56px;padding:8px 12px"></textarea></div><button class="btn primary" id="sv">Save disbursement</button></form><div class="card"><b>Disbursement records</b><div class="empty">No disbursement yet</div></div></div>`;
  const f = out.querySelector('#df'); f.onchange = () => f.querySelector('#rf').hidden = f.method.value !== 'bank_transfer';
  f.onsubmit = async (e) => { e.preventDefault(); f.querySelectorAll('.err').forEach((x) => x.remove()); const v = Object.fromEntries(new FormData(f)); if (!v.reference) delete v.reference; if (!v.note) delete v.note;
    try { await ChitService.disburse(id, v); toast('Disbursement saved'); await load(); render(); } catch (err) { showErrors(f, err); toast(err.message); } };
}
const V = [() => `<div class="grid4"><div class="card dark"><small>Total repayment</small><div class="v">${esc(c.total_repayment)}</div><small>${esc(c.installment_amount)}</small></div><div class="card"><small>Paid</small><div class="v g">${esc(c.paid)}</div><small>${c.paid_installments} of ${c.installment_count}</small></div><div class="card"><small>Outstanding</small><div class="v">${esc(c.outstanding)}</div></div><div class="card"><small>Loan amount</small><div class="v">${esc(c.loan_amount)}</div><small>Given to the customer</small></div></div>
  <div class="two"><div class="card"><b>Terms</b>${dl({ Customer: esc(c.customer || '—'), 'Loan amount': c.loan_amount, Repayment: esc(c.installment_amount) + ' ' + (c.frequency || ''), Installments: c.installment_count, Start: c.start_date, End: c.end_date })}</div><div class="card"><b>Progress</b><table style="margin-top:8px"><thead><tr><th></th><th class="r">Amount</th><th class="r">Installments</th></tr></thead><tbody><tr><td>Total repayment</td><td class="r">${esc(c.total_repayment)}</td><td class="r">${c.installment_count}</td></tr><tr><td>Paid</td><td class="r">${esc(c.paid)}</td><td class="r">${c.paid_installments}</td></tr><tr><td><b>Remaining</b></td><td class="r"><b>${esc(c.outstanding)}</b></td><td class="r"><b>${c.installment_count - c.paid_installments}</b></td></tr></tbody></table><div class="bar" style="margin-top:14px"><i style="width:${Math.min(100, c.paid_installments / c.installment_count * 100)}%"></i></div><small style="color:var(--muted)">${Math.round(c.paid_installments / c.installment_count * 100)}% repaid</small></div></div>`,
  schedule, async () => { loading(out); const p = (await PaymentService.list()).filter((x) => String(x.chitId) === String(id)); out.innerHTML = table([{ h: 'Receipt', f: (x) => x.receipt }, { h: 'Date & time', f: (x) => x.when }, { h: 'Method', f: (x) => `<span class="pill off">${x.method}</span>` }, { h: 'Collected by / ref', f: (x) => esc(x.ref || x.by) }, { h: 'Amount', f: (x) => fmt.money(x.amount), r: 1 }, { h: 'Status', f: (x) => pill(x.status) }], p, 'No payments yet.'); }, disbursement, () => '<div class="empty">No audit entries.</div>'];
function render() { document.getElementById('nm').textContent = c.chit_code; document.getElementById('sub').innerHTML = `${c.customer ? esc(c.customer) + ' · ' : ''}${pill(c.status)}`;
  document.getElementById('crumb').innerHTML = `<a href="index.html">Chit accounts</a> / ${c.chit_code}`;
  const a = document.getElementById('acts'); a.style.cssText = 'display:flex;gap:8px'; a.innerHTML = (c.status === 'pending' ? '<button class="btn primary" id="rd">Record disbursement</button>' : '') + (c.status === 'active' || c.status === 'pending' ? '<button class="btn danger" id="cx">Cancel chit</button>' : '');
  const rd = a.querySelector('#rd'); if (rd) rd.onclick = () => document.querySelectorAll('#tabs button')[3].click();
  if (a.querySelector('#cx')) a.querySelector('#cx').onclick = () => modal({ title: `Cancel ${c.chit_code}?`, body: '<p style="color:var(--muted)">This stops the schedule. Payments already made stay in the ledger.</p><div class="field l" style="margin-top:10px"><label>Reason *</label><textarea class="input" id="rs" style="height:64px"></textarea></div>', actions: [{ label: 'Back' }, { label: 'Cancel chit', kind: 'danger', onClick: async (cl, b, o) => { const rs = o.querySelector('#rs').value.trim(); if (!rs) return toast('Reason is required'); try { await ChitService.cancel(c.id, rs); cl(); toast('Chit cancelled'); await load(); render(); } catch (e) { toast(e.message); } } }] });
  const t = +(P.get('tab') || 0); tabs(document.getElementById('tabs'), ['Overview', 'Schedule', 'Payments', 'Disbursement', 'Audit'], (i) => { const r = V[i](); if (typeof r === 'string') out.innerHTML = r; else r?.catch((e) => failed(out, e)); }, t); const r = V[t](); if (typeof r === 'string') out.innerHTML = r; else r?.catch((e) => failed(out, e)); }
loading(out); load().then(render).catch((e) => failed(out, e));
