mountShell('settings'); const out = document.getElementById('out');
const f = (l, k, s, t = 'text') => `<div class="field l"><label>${l}</label><input class="input" name="${k}" type="${t}" value="${esc(s[k])}"></div>`;
const PANES = [(s) => f('Company name', 'company', s) + f('Support phone', 'phone', s) + f('Office hours', 'hours', s) + f('Receipt number prefix', 'prefix', s) + '<div class="hint" style="margin:-8px 0 12px">Receipts look like THD-RCP-000124</div>',
  (s) => f('Wrong PIN attempts before lock', 'pinAttempts', s, 'number') + f('Lock duration (minutes)', 'lockMinutes', s, 'number') + f('Session timeout (minutes)', 'sessionMinutes', s, 'number'),
  (s) => `<div class="field l"><label>Mode</label><select class="input" name="mode"><option>Test</option><option>Live</option></select></div>` + dl({ 'Key ID': esc(s.keyId), Webhook: '<span class="pill">Receiving</span>', 'Last webhook': 'Today, 10:02 am' }) + '<div class="hint" style="margin:8px 0 12px">Payments count only after the server verifies them.</div>',
  (s) => `<div class="kv"><span>Enable push notifications<br><small>Not needed for V1. The system is ready for it later.</small></span><button type="button" class="tgl ${s.push ? 'on' : ''}" id="tg" aria-pressed="${s.push}"></button></div>`];
const SIDE = [['Numbering', { 'Customer ID format': 'THD-10xxx', 'Chit account format': 'THD-xxxx', 'Agent ID format': 'AGT-xxx' }], ['Login and PIN rules', { Login: 'Mobile number + PIN', 'Who uses it': 'Customers, agents and admins', 'PIN length': '4 digits', Storage: 'Secure hash only', Reset: 'By admin, temporary PIN shown once' }, 'One login screen for everyone. The app opens the right side for each role.'], ['Duplicate protection', { 'Repeat Razorpay callbacks': 'Ignored', 'Cash entries': 'Recorded once, corrected only by approval' }], null];
const HEAD = ['Company & support', 'Login protection', 'Razorpay', 'Push notifications'];
async function show(i) { loading(out); const s = await SettingsService.get();
  const side = SIDE[i] ? `<div class="card"><b>${SIDE[i][0]}</b><div style="margin-top:8px">${dl(SIDE[i][1])}</div></div>` : '';
  out.innerHTML = `<div class="two" style="grid-template-columns:1fr ${side ? '1fr' : ''}"><form class="card" id="sf"><b style="display:block;margin-bottom:12px">${HEAD[i]}</b>${PANES[i](s)}<button class="btn primary" style="margin-top:8px">Save</button></form>${side}</div>`;
  const tg = out.querySelector('#tg'); if (tg) tg.onclick = async () => { tg.classList.toggle('on'); s.push = tg.classList.contains('on'); await SettingsService.save({ push: s.push }); toast('Settings saved (local demo only)'); };
  out.querySelector('#sf').onsubmit = async (e) => { e.preventDefault(); const v = Object.fromEntries(new FormData(e.target)); if (tg) v.push = s.push; await SettingsService.save(v); toast('Settings saved (local demo only)'); }; }
tabs(document.getElementById('tabs'), ['General', 'Security', 'Payments', 'Notifications'], show); show(0);
